export const REGION_NAMES = [
  'Asia',
  'North America',
  'Latin America',
  'Europe',
  'Middle East & North Africa',
  'Sub-Saharan Africa',
  'Oceania',
] as const;

export type RegionName = (typeof REGION_NAMES)[number];
export type RegionId = RegionName | 'Other';

export const REGION_COLOR: Record<RegionId, string> = {
  Asia: '#00d2ff',
  'North America': '#8b6cff',
  'Latin America': '#3ee0b0',
  Europe: '#ffb020',
  'Middle East & North Africa': '#ff7a59',
  'Sub-Saharan Africa': '#f2d56b',
  Oceania: '#7dffc3',
  Other: '#9aa3b8',
};

const REGION_BY_CODE: Record<string, RegionName> = {
  IN: 'Asia',
  ID: 'Asia',
  PH: 'Asia',
  MY: 'Asia',
  PK: 'Asia',
  CN: 'Asia',
  VN: 'Asia',
  TH: 'Asia',
  SG: 'Asia',
  KR: 'Asia',
  BD: 'Asia',
  TW: 'Asia',
  HK: 'Asia',
  JP: 'Asia',
  NP: 'Asia',
  LK: 'Asia',
  KH: 'Asia',
  MM: 'Asia',
  KZ: 'Asia',
  UZ: 'Asia',
  MN: 'Asia',
  AF: 'Asia',
  MO: 'Asia',
  KP: 'Asia',
  AZ: 'Asia',
  US: 'North America',
  CA: 'North America',
  MX: 'North America',
  BR: 'Latin America',
  AR: 'Latin America',
  CO: 'Latin America',
  PE: 'Latin America',
  CL: 'Latin America',
  VE: 'Latin America',
  EC: 'Latin America',
  DO: 'Latin America',
  CR: 'Latin America',
  BO: 'Latin America',
  GT: 'Latin America',
  UY: 'Latin America',
  PR: 'Latin America',
  PA: 'Latin America',
  PY: 'Latin America',
  JM: 'Latin America',
  CU: 'Latin America',
  GB: 'Europe',
  RU: 'Europe',
  UA: 'Europe',
  RS: 'Europe',
  ES: 'Europe',
  IT: 'Europe',
  DE: 'Europe',
  FR: 'Europe',
  NL: 'Europe',
  PL: 'Europe',
  PT: 'Europe',
  DK: 'Europe',
  CH: 'Europe',
  SE: 'Europe',
  RO: 'Europe',
  BE: 'Europe',
  IE: 'Europe',
  FI: 'Europe',
  NO: 'Europe',
  CZ: 'Europe',
  AT: 'Europe',
  HU: 'Europe',
  GR: 'Europe',
  BG: 'Europe',
  SK: 'Europe',
  LT: 'Europe',
  HR: 'Europe',
  LU: 'Europe',
  CY: 'Europe',
  EE: 'Europe',
  MT: 'Europe',
  SI: 'Europe',
  LV: 'Europe',
  IS: 'Europe',
  ME: 'Europe',
  MD: 'Europe',
  BY: 'Europe',
  AL: 'Europe',
  BA: 'Europe',
  GE: 'Europe',
  AM: 'Europe',
  SA: 'Middle East & North Africa',
  AE: 'Middle East & North Africa',
  EG: 'Middle East & North Africa',
  TR: 'Middle East & North Africa',
  IQ: 'Middle East & North Africa',
  JO: 'Middle East & North Africa',
  LB: 'Middle East & North Africa',
  KW: 'Middle East & North Africa',
  OM: 'Middle East & North Africa',
  BH: 'Middle East & North Africa',
  QA: 'Middle East & North Africa',
  IR: 'Middle East & North Africa',
  IL: 'Middle East & North Africa',
  PS: 'Middle East & North Africa',
  SY: 'Middle East & North Africa',
  YE: 'Middle East & North Africa',
  MA: 'Middle East & North Africa',
  DZ: 'Middle East & North Africa',
  TN: 'Middle East & North Africa',
  LY: 'Middle East & North Africa',
  SD: 'Middle East & North Africa',
  ZA: 'Sub-Saharan Africa',
  NG: 'Sub-Saharan Africa',
  KE: 'Sub-Saharan Africa',
  GH: 'Sub-Saharan Africa',
  TZ: 'Sub-Saharan Africa',
  UG: 'Sub-Saharan Africa',
  CM: 'Sub-Saharan Africa',
  ET: 'Sub-Saharan Africa',
  MZ: 'Sub-Saharan Africa',
  ZM: 'Sub-Saharan Africa',
  ZW: 'Sub-Saharan Africa',
  AU: 'Oceania',
  NZ: 'Oceania',
};

export function regionOf(code: string): RegionId {
  return REGION_BY_CODE[code] ?? 'Other';
}
